### ISSUE TITLE
y u no inheritance

### ISSUE THREAD

**Issue by juliangruber** [mafintosh/multi-random-access#1]
Is there a particular reason this isn't inheriting from abstract-random-access, to gain arg checking / defaults etc.?

**Comment by mafintosh** [comment]
![patience](http://www.fandomfollowing.com/wp-content/uploads/2016/04/patience-my-friend.gif)

**Comment by juliangruber** [comment]
https://github.com/mafintosh/multi-random-access/commit/65b400a69977abf0a707c7353681147fd2623c5c
